remote_theme: tonylokko/just-the-docs
logo: "logo.svg"
color_scheme: strongdmdark


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
