version: "3.9"
services:
  log-export-container:
    build: .
    # image: log-export-container:latest
    ports:
      - "5140:5140"
    environment:
      # IMPORTANT: Do not enclose values in double or single quotes 

      # Required variables
      - LOG_EXPORT_CONTAINER_INPUT=json # possible values = json or csv
      - LOG_EXPORT_CONTAINER_OUTPUT=stdout # possible values = stdout or s3
    
      # Optional variables
      # When using LOG_EXPORT_CONTAINER_OUTPUT=s3 add variables listed in docs/CONFIGURE_S3.md
