name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
        with:
          ruby-version: '3.4'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: ruby test/run_test.rb
      - name: Run RSpec Tests
        run: bundle exec rspec test
